#!/bin/sh

uci -q batch <<-EOF 2>&1 >/dev/null
	delete ucitrack.@AdGuardHome[-1]
	add ucitrack AdGuardHome
	set ucitrack.@AdGuardHome[-1].init=AdGuardHome
	commit ucitrack
	delete AdGuardHome.AdGuardHome.ucitracktest
EOF

rm -f /tmp/luci-indexcache
exit 0
